# IremiaMinigameAPI Configuration

minigames:
  # Default player limits
  default-min-players: 2
  default-max-players: 16
  
  # Timing settings
  default-countdown-seconds: 10
  default-game-duration-seconds: 300
  
  # Performance settings
  player-cache-cleanup-interval: 30
  max-cached-players: 100
  
  # Messages
  messages:
    game-full: "This game is full!"
    game-in-progress: "This game is already in progress!"
    not-enough-players: "Not enough players to start!"
    players-remaining: "Not enough players remaining! Ending game."
    countdown-cancelled: "Countdown cancelled - not enough players!"
